[build]
  publish = "dist"
  command = "pnpm build"

[functions]
  directory = "api"

[dev]
  command = "pnpm dev"
  publish = "dist"
  port = 8889
  targetPort = 5176

# Handle auth routes - redirect /api/auth/* to netlify function
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Handle SPA routing - must come last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200